###############################################################################
#                          Generated on docker.io                          #
###############################################################################
version: "3.5"
services:
    mysql:
      image: mariadb
      container_name: docker-symfony6-mysql
      working_dir: /application
      volumes:
        - .:/application
      environment:
        - MYSQL_ROOT_PASSWORD=dbrootpw
        - MYSQL_DATABASE=docker_symfony6
        - MYSQL_USER=dbuserf
        - MYSQL_PASSWORD=dbpw
      ports:
        - "8002:3306"
    nginx:
      image: nginx:alpine
      container_name: docker-symfony6-webserver
      working_dir: /application
      volumes:
          - .:/application
          - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      ports:
        - "8000:80"
    php-fpm:
      build: docker/php-fpm
      container_name: docker-symfony6-php-fpm
      working_dir: /application
      expose:
        - 9000
      volumes:
        - .:/application
        - ./docker/php-fpm/configs/php-ini-overrides.ini:/usr/local/etc/php/conf.d/zza-custom.ini
        - ./docker/php-fpm/tmp:/tmp
    rabbitmq:
      image: rabbitmq:management
      container_name: rabbitmq
      hostname: rabbitmq
      restart: always
      environment:
        - RABBITMQ_DEFAULT_USER=guest
        - RABBITMQ_DEFAULT_PASS=guest
        - RABBITMQ_SERVER_ADDITIONAL_ERL_ARGS=-rabbit disk_free_limit 2147483648
      ports:
        - "5672:5672"
        - "15672:15672"
    php-receiver:
      build: docker/php-receiver
      container_name: rabbit-consumer
      working_dir: /application/src/public/
      command: "php ./rabbit_consumer.php"
      restart: always
      volumes:
        - .:/application
      depends_on:
        - rabbitmq
      links:
        - rabbitmq
